// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	google_books "books_online_api/business/google_books"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ThirdPartyGoogleBooks is an autogenerated mock type for the ThirdPartyGoogleBooks type
type ThirdPartyGoogleBooks struct {
	mock.Mock
}

// SearchBooks provides a mock function with given fields: ctx, keyword, startIndex, maxResult
func (_m *ThirdPartyGoogleBooks) SearchBooks(ctx context.Context, keyword string, startIndex int, maxResult int) ([]google_books.Domain, error) {
	ret := _m.Called(ctx, keyword, startIndex, maxResult)

	var r0 []google_books.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []google_books.Domain); ok {
		r0 = rf(ctx, keyword, startIndex, maxResult)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]google_books.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, keyword, startIndex, maxResult)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
