// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	transactions "books_online_api/business/transactions"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateTransactions provides a mock function with given fields: ctx, domain
func (_m *Repository) CreateTransactions(ctx context.Context, domain transactions.Domain) (transactions.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 transactions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, transactions.Domain) transactions.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(transactions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, transactions.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusTransaction provides a mock function with given fields: ctx, domain
func (_m *Repository) UpdateStatusTransaction(ctx context.Context, domain transactions.Domain) (transactions.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 transactions.Domain
	if rf, ok := ret.Get(0).(func(context.Context, transactions.Domain) transactions.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(transactions.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, transactions.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
