// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	book_types "books_online_api/business/book_types"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateBookType provides a mock function with given fields: ctx, bookType
func (_m *Repository) CreateBookType(ctx context.Context, bookType book_types.Domain) (book_types.Domain, error) {
	ret := _m.Called(ctx, bookType)

	var r0 book_types.Domain
	if rf, ok := ret.Get(0).(func(context.Context, book_types.Domain) book_types.Domain); ok {
		r0 = rf(ctx, bookType)
	} else {
		r0 = ret.Get(0).(book_types.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, book_types.Domain) error); ok {
		r1 = rf(ctx, bookType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
