// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	books "books_online_api/business/books"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Localy is an autogenerated mock type for the Localy type
type Localy struct {
	mock.Mock
}

// CreateBook provides a mock function with given fields: ctx, _a1
func (_m *Localy) CreateBook(ctx context.Context, _a1 books.Domain) (books.Domain, error) {
	ret := _m.Called(ctx, _a1)

	var r0 books.Domain
	if rf, ok := ret.Get(0).(func(context.Context, books.Domain) books.Domain); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(books.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, books.Domain) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
