// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	payment_methods "books_online_api/business/payment_methods"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreatePaymentMethod provides a mock function with given fields: ctx, domain
func (_m *Repository) CreatePaymentMethod(ctx context.Context, domain payment_methods.Domain) (payment_methods.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 payment_methods.Domain
	if rf, ok := ret.Get(0).(func(context.Context, payment_methods.Domain) payment_methods.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(payment_methods.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, payment_methods.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOnePaymentMethod provides a mock function with given fields: ctx, domain
func (_m *Repository) GetOnePaymentMethod(ctx context.Context, domain payment_methods.Domain) (payment_methods.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 payment_methods.Domain
	if rf, ok := ret.Get(0).(func(context.Context, payment_methods.Domain) payment_methods.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(payment_methods.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, payment_methods.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
