name: unit test golang
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
#  job 1: unit test
  unit-test:
    name: do unit test to project go
    runs-on: ubuntu-latest
    steps:
    - name: setup github action (CI)
      uses: actions/checkout@v2
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: running unit test
      uses: go test ./... -cover