name: unit test golang
on:
  push:
    branches:
      - 'master'
      - 'ci'
  pull_request:
    branches:
      - 'master'

jobs:
  config:
    name: do create config file
    runs-on: ubuntu-latest
    steps:
      - name: running echo
        run: |
          echo '{
          "debug":true,
          "server":{"address":"${{ secrets.SERVER_ADDRESS }}"},
          "context":{"timeout":2},
          "database":{
            "prod":{
              "host": "${{ secrets.HOST_DATABASE }}",
              "port": "${{ secrets.PORT_DATABASE }}",
              "user": "${{ secrets.USER_DATABASE }}",
              "pass": "${{ secrets.PASSWORD_DATABASE }}"
            }
          }
          "jwt": {
            "secret": "${{ secrets.JWT_SECRET }}",
            "expired": 72
          }
          }' >> config.json

  #  job 1: unit test
  unit-test:
    name: do unit test to project go
    runs-on: ubuntu-latest
    needs: config
    steps:
    - name: setup github action (CI)
      uses: actions/checkout@v2
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: running unit test
      run: go test ./... -cover

# job 2: build push docker
  build-push-docker:
    name: "Build image and push register"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: build docker
        run: docker build -t wahyunf354/books_online:1.0.0 .
      - name: login registry docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: push docker hub
        run: docker push wahyunf354/books_online:1.0.0

  deployment-ec2:
    name: "Deploy to ec2 from registry docker hub"
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2
      - name: configuration SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/books_online.pem
          chmod 400 ~/.ssh/books_online.pem
          cat >>~/.ssh/config <<END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/books_online.pem
            StrictHostKeyChecking=no
          END
      - name: Connect EC2 & Remove All Container & Pull from Registry & Start
        run: ssh development 'docker rm -f $(docker ps -a -q) && docker pull wahyunf354/books_online:1.0.0 && docker run -d -p 8080:8080 --name=books_online wahyunf354/books-online:1.0.0'

