name: unit test golang
on:
  push:
    branches:
      - 'master'
      - 'ci'
  pull_request:
    branches:
      - 'master'

jobs:
#  job 1: unit test
  unit-test:
    name: do unit test to project go
    runs-on: ubuntu-latest
    steps:
    - name: setup github action (CI)
      uses: actions/checkout@v2
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: running unit test
      run: go test ./... -cover

  build-push-docker:
    name: "Build image and push register"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: build docker
        run: docker build -t wahyunf354/books_online:1.0.0 .
      - name: login registry docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USENAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: push docker hub
        run: docker push wahyunf354/books_online:1.0.0

